name: version auto-incrementing, coverage testing, & package publishing
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: ["master"]

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install uv and set the python version per the .python-version file
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.6.3"
    
      - name: Finalize virtual env
        run: uv sync --all-groups --all-extras

      - name: Increment version
        run: uv run python ./.github/workflows/version.py --increment

      - name: Run tests and generate coverage badge
        run: |
          uv run coverage run test/test.py
          uv run coverage report -m sigfig/sigfig.py
          rm test/coverage.svg
          uv run coverage-badge -o test/coverage.svg

      - name: Build docs
        run: |
          cd doc
          uv run make html

      - name: Bundle for PyPI and check
        run: |
          uv run python -m build
          uv run twine check dist/*

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "increment to v$(uv run python ./.github/workflows/version.py --get)"
          git push --force

      - name: Build package
        run: |
          uv run python -m build
          uv run twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
