name: Test with oldest supported Python version (3.6)
on:
  pull_request:

jobs:
  oldest_supported_version_test:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install uv and override the python version
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.6.3"
          python-version: "3.6.7"

      - name: Finalize virtual env
        run: uv sync --all-groups --all-extras

      - name: Run tests
        run: python test/test.py
